[build]
  command = "CI=false npm run build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"
  framework = "vite"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
