[build]
  command = "CI=false npm run build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --force"
  CI = "false"
  NETLIFY_USE_YARN = "false"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Allow-Credentials = "true"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"
  framework = "vite"

[[redirects]]
  from = "/api/*"
  to = "https://api.groq.com/openai/v1/chat/completions/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Credentials = "true"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
